language: node_js
node_js:
  - "8"
services: mongodb
cache:
  npm: true
install:
  - npm install
script:
  - npm install codecov -g
  - npm run build
  - npm t -- --coverage
after_success:
  - codecov
deploy:
  provider: npm
  email: jcguarinpenaranda@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true